### ISSUE TITLE
Please add my lib

### ISSUE THREAD

**Issue by namuyan** [Sateetje/ProjectsUsingNEM#8]
Hello,
I'm a maintainer of [nem-python](https://github.com/namuyan/nem-python) library.
Please add [Wrappers](https://github.com/Sateetje/awesome-nem-projects#wrappers) section.
Thank you and best regards.
description: Not require NIS running on local, sign on offline and  transaction builder API library

**Comment by Sateetje** [comment]
Done.

Thanks!
